POST http://localhost:5000/users
Content-Type: application/json

{
    "username": "test3",
    "password": "test2",
    "email": "test@test.com",
}

###

GET http://localhost:5000/users/6029bf89629a281e6cd4c181

###
PATCH  http://localhost:5000/users/6029bf89629a281e6cd4c181
Content-Type: application/json

{
    "session": "patch_successful"
}


###
GET http://localhost:5000/shows

###
GET http://localhost:5000/shows/602ec6920577781c14c89b25

###

POST http://localhost:5000/shows
Content-Type: application/json

{
    "title": "test3",
    "genre": "test2",
    "description": "test@test.com",
    "rating": 3,
    "tags": ["one", "two", "three"],
    "likes":0
}

###
PATCH http://localhost:5000/shows/602ec1e6ed9fbe2efcf5c051
Content-Type: application/json

{
    "title": "test9",
    "genre": "test3"
}
ss
###
DELETE http://localhost:5000/shows/6000704ae7945bff0edd86eb

###
POST http://localhost:5000/users/login
Content-Type: application/json

{
    "username": "jon",
    "password": "password"
}

###
GET http://localhost:5000/shows

###